name: Java CI Cresco Client Lib

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: print env
        run: echo $SONATYPE_USERNAME
        env:
           SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
           SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      #- name: Build with Maven
      #  run: mvn clean package
      #- name: Deploy to Maven
      #  run: mvn deploy:deploy-file -Dfile=target/clientlib-1.1-SNAPSHOT.jar -Durl=https://oss.sonatype.org/content/repositories/snapshots -DrepositoryId=ossrh -DpomFile=pom.xml --settings ci-settings.xml -DskipTests=true -B
      #  env:
      #    SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      #    SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}