name: Java CI Cresco Client Lib

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
            serverUrl: https://oss.sonatype.org/content/repositories/snapshots
            username: ${{ secrets.SONATYPE_USERNAME }}
            password: ${{ secrets.SONATYPE_PASSWORD }}
            format: maven2
            repository: ossrh
            coordinates: groupId=io.cresco artifactId=clientlib version=1.1-SNAPSHOT
            assets: extension=jar
            filename: ./target/clientlib-1.1-SNAPSHOT.jar